version: '3'

services:
  purchaser:
    build:
      context: .
      dockerfile: Dockerfile
    command: -port 8080 -dbfile /data/purchases.db
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
